"""
Test Stateful Agent with Semantic Memory
Demonstrates Phase 6: Agents remember context across conversations
"""

import sys
from pathlib import Path
sys.path.append(str(Path(__file__).parent.parent))

from src.memory.conversation_memory import ConversationMemory
from src.memory.semantic_index import SemanticIndex


class StatefulHRAgent:
    """
    HR Agent with semantic memory
    
    This implements your Phase 6 architectural decision:
    - Store full conversation
    - Chunk into embeddable units
    - Retrieve only relevant context via semantic search with Azure OpenAI
    """
    
    def __init__(self):
        self.memory = ConversationMemory()
        self.index = SemanticIndex()
        self.agent_id = "hr-agent"
    
    def start_session(self, user_id: str) -> str:
        """Start a new conversation session"""
        return self.memory.start_conversation(user_id, self.agent_id)
    
    def query(
        self,
        conversation_id: str,
        user_query: str,
        use_semantic_search: bool = True
    ) -> str:
        """
        Process user query with memory
        
        Args:
            conversation_id: Conversation identifier
            user_query: User's question
            use_semantic_search: Whether to use semantic retrieval
            
        Returns:
            Agent response
        """
        
        # Add user turn to memory
        self.memory.add_turn(
            conversation_id,
            role="user",
            content=user_query,
            tokens=len(user_query.split()) * 2  # Rough estimate
        )
        
        # Retrieve relevant context
        if use_semantic_search:
            # Phase 6 approach: Semantic search with Azure OpenAI embeddings
            
            # Get conversation chunks
            chunks = self.memory.chunk_conversation(conversation_id)
            
            # Index chunks (embeddings auto-generated by Azure OpenAI)
            for chunk in chunks:
                # Check if chunk already indexed (avoid re-indexing)
                chunk_exists = any(
                    c.chunk_id == chunk["chunk_id"] 
                    for c in self.index.chunks
                )
                
                if not chunk_exists:
                    self.index.add_chunk(
                        chunk_id=chunk["chunk_id"],
                        conversation_id=conversation_id,
                        content=chunk["content"],
                        # embedding auto-generated
                        metadata=chunk
                    )
            
            # Search for relevant chunks using Azure OpenAI
            relevant_chunks = self.index.search(
                query=user_query,  # Azure generates query embedding
                top_k=3,
                conversation_id=conversation_id
            )
            
            context_info = f"Found {len(relevant_chunks)} relevant past discussions"
            if relevant_chunks:
                most_relevant = relevant_chunks[0]
                context_preview = most_relevant["content"]
                similarity_score = most_relevant["similarity"]
                print(f"   🔍 Most relevant memory (similarity: {similarity_score:.4f})")
            else:
                context_preview = "No previous context"
        else:
            # Baseline approach: Recent context
            recent_context = self.memory.get_recent_context(
                conversation_id,
                max_turns=10
            )
            context_info = f"Using {len(recent_context)} recent turns"
            context_preview = "Recent conversation history"
        
        # Simulate agent response (in production, this would call GPT-4o)
        response = self._generate_response(user_query, context_preview, use_semantic_search)
        
        # Add assistant turn to memory
        self.memory.add_turn(
            conversation_id,
            role="assistant",
            content=response,
            agent_id=self.agent_id,
            tokens=len(response.split()) * 2
        )
        
        return response
    
    def _generate_response(self, query: str, context: str, semantic: bool) -> str:
        """
        Simulate agent response
        
        In production, this would call GPT-4o with:
        system_prompt + semantic_context + query
        """
        
        query_lower = query.lower()
        context_lower = context.lower()
        
        # Simulate intelligent responses based on context
        if "parental leave" in query_lower and "parental leave" in context_lower:
            return "Based on our previous discussion, parental leave is 12 weeks paid at 100% of base salary under the Family Benefits Policy. Is there anything specific about parental leave you'd like to know more about?"
        
        elif "enrollment forms" in query_lower and "enrollment forms" in context_lower:
            return "Of course! I'll send the benefits enrollment forms we discussed earlier. You should receive them within 24 hours. They cover health insurance, 401k, and other benefits."
        
        elif "pto" in query_lower or "vacation" in query_lower:
            return "New employees receive 15 days of PTO in their first year, increasing to 20 days after 2 years of service."
        
        elif "benefits" in query_lower and "benefits" in context_lower:
            return "You're eligible for benefits after 60 days. This includes health insurance, 401k, and paid parental leave. Would you like details on any specific benefit?"
        
        else:
            if semantic:
                return f"I found relevant information from our previous conversations. How can I help you further?"
            else:
                return "I'd be happy to help! Could you provide more details?"


def main():
    print("🧪 Testing Stateful Agent with Azure OpenAI Semantic Memory\n")
    
    agent = StatefulHRAgent()
    
    print("\n" + "="*60)
    print("Scenario: Dr. Chen's Multi-Day Conversation")
    print("="*60)
    print()
    
    # Day 1 (9 AM) - Initial conversation
    print("📅 DAY 1 (9 AM) - Initial Conversation")
    print("-"*60)
    
    conv_id = agent.start_session(user_id="EMP-PHYSICIAN-042")
    print(f"Started session: {conv_id}\n")
    
    queries_day1 = [
        "When do I get my benefits?",
        "What's the parental leave policy?",
        "That's great, thank you!"
    ]
    
    for query in queries_day1:
        print(f"👤 Dr. Chen: {query}")
        response = agent.query(conv_id, query, use_semantic_search=False)
        print(f"🤖 HR Agent: {response}\n")
    
    # Day 3 (10 AM) - Follow-up with semantic search
    print("="*60)
    print("📅 DAY 3 (10 AM) - Follow-up Question")
    print("="*60)
    print()
    
    print("🔍 Agent using AZURE OPENAI SEMANTIC SEARCH\n")
    
    query_day3 = "What did we discuss about parental leave?"
    
    print(f"👤 Dr. Chen: {query_day3}")
    response = agent.query(conv_id, query_day3, use_semantic_search=True)
    print(f"🤖 HR Agent: {response}\n")
    
    # Another semantic search query
    print("="*60)
    print("Another Follow-up")
    print("="*60)
    print()
    
    query_day3_2 = "Can you send those enrollment forms?"
    
    print(f"👤 Dr. Chen: {query_day3_2}")
    response = agent.query(conv_id, query_day3_2, use_semantic_search=True)
    print(f"🤖 HR Agent: {response}\n")
    
    # Show memory stats
    print("="*60)
    print("📊 Memory Statistics")
    print("="*60)
    print()
    
    summary = agent.memory.get_conversation_summary(conv_id)
    print(f"Conversation: {summary['conversation_id']}")
    print(f"Total Turns: {summary['turn_count']}")
    print(f"Total Tokens: {summary['total_tokens']}")
    print(f"Chunks Indexed: {len(agent.index.chunks)}")
    print(f"Started: {summary['started_at']}")
    print(f"Last Updated: {summary['last_updated']}")
    
    print("\n" + "="*60)
    print("✅ Stateful Agent Tests Complete")
    print("="*60)
    print()
    
    print("🎯 Key Achievements:")
    print("  ✓ Azure OpenAI embeddings for semantic search")
    print("  ✓ Multi-day conversation memory")
    print("  ✓ Intelligent context retrieval (relevant chunks only)")
    print("  ✓ Natural conversation continuity")
    print()
    print("💡 Production Impact:")
    print("  • Users feel like the AI 'remembers' them")
    print("  • Cost-efficient (retrieve 500 tokens, not 12,000)")
    print("  • Scalable to long-term relationships")


if __name__ == "__main__":
    main()